#!/bin/bash

patchdir=$1 #e.g., ./patch/plausible
rsltdir=$2 #e.g., ./candidates/plausible

for f in ${patchdir}/*
do
    fname=$(basename ${f})
    name0=$(echo ${fname} | cut -d "_" -f 1)
    name1=$(echo ${fname} | cut -d "_" -f 2)
    bugid=${name0}_${name1}
    logf=/home/qx5/ssFix2/test/repair_all_bugs/log/${bugid}

    ./cp_candidate ${bugid} ${logf} ${rsltdir} 
done
