#!/bin/bash

for i in {5,13,15,26}
do
    cp ~/data/defects4j-0.1.0-projects/Chart/patches/${i}.src.patch ./developer/Chart_${i}
done

for i in {7,22,27,39}
do
    cp ~/data/defects4j-0.1.0-projects/Lang/patches/${i}.src.patch ./developer/Lang_${i}
done

for i in {40,49,50,78,80,81,82,84,85}
do
    cp ~/data/defects4j-0.1.0-projects/Math/patches/${i}.src.patch ./developer/Math_${i}
done

cp ~/data/defects4j-0.1.0-projects/Closure/patches/85.src.patch ./developer/Closure_85

