#!/bin/bash

if [ ! -d rslt ]; then
    mkdir rslt
fi

ssfixdir=$PWD/..
l21dir=$PWD/Lang_21_buggy
rsltdir=$PWD/rslt

${ssfixdir}/run -bugid l21 -dependjpath ${l21dir}/all0.jar -projdpath ${l21dir} -projsrcdpath ${l21dir}/src/main/java -projbuilddpath ${l21dir}/target/classes -projtestbuilddpath ${l21dir}/target/test-classes -outputdpath ${rsltdir} -ssfixdpath ${ssfixdir} -tsuitefpath ${l21dir}/testsuite_classes -faulocfpath ${l21dir}/gzoltar_fauloc -faulocaddstacktrace -parallelgranularity 4 &> lang21_log
