#!/bin/bash

ssfix_lib_dir=$PWD/../lib
l21dir=$PWD/Lang_21_buggy

java -cp :${ssfix_lib_dir}/* edu.brown.cs.cocker.application.ApplicationChunkQuery -a ssfix -data "slc:4,1" ./Lang_21_buggy/HelloWorld.java &> lang21_codesearch_rslt
