#!/bin/bash

for i in {5,12,13}
do
    cp ~/data/defects4j-0.1.0-projects/Chart/patches/${i}.src.patch ./developer/Chart_${i}
done

for i in {7,22,39}
do
    cp ~/data/defects4j-0.1.0-projects/Lang/patches/${i}.src.patch ./developer/Lang_${i}
done

for i in {8,49,50,53,60,70,73,74,78,80,81,85,95}
do
    cp ~/data/defects4j-0.1.0-projects/Math/patches/${i}.src.patch ./developer/Math_${i}
done

