#!/bin/bash

for i in {3,5,6,13,26}
do
    cp ~/data/defects4j-0.1.0-projects/Chart/patches/${i}.src.patch ./developer/Chart_${i}
done

for i in {44,51,58}
do
    cp ~/data/defects4j-0.1.0-projects/Lang/patches/${i}.src.patch ./developer/Lang_${i}
done

for i in {33,40,49,50,57,58,71,73,81,85,87,99,104}
do
    cp ~/data/defects4j-0.1.0-projects/Math/patches/${i}.src.patch ./developer/Math_${i}
done

for i in {2,3,12,33,40,45,55,62,63,113,115,133}
do
    cp ~/data/defects4j-0.1.0-projects/Closure/patches/${i}.src.patch ./developer/Closure_${i}
done

